# DO NOT TOUCH THIS FILE
# Please speak to SudoVanilla (Korbs) if you have any issues.
# For Security check please contact Eveeifyeve Instead of sudovanilla.

name: Deploy Website

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:


  #Screenshot of website

  # screenshot:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #        persist-credentials: true

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20' # or any version you prefer

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run server
  #       run: |
  #         npm run start &
  #         echo "NODE_PID=$!" >> $GITHUB_ENV
  #         sleep 6 # give the server some time to start

  #     - name: Install bun
  #       run: npm install -g bun

  #     - name: Take screenshot
  #       run: |
  #        npm run screenshot

  #     - name: Stop server
  #       run: kill ${{ env.NODE_PID }} # this will kill the process started by npm start

  #     - name: Commit and push if it changed
  #     run: |
  #      git config --global user.name 'Your Name'
  #      git config --global user.email 'your-username@users.noreply.github.com'
  #      git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
  #      git checkout "${GITHUB_REF:11}"
  #      git commit -am "Automated Screenshot"
  #      git push


# ---------------------------------------------------------------------


  # Checks the linting of the website
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run Stylelint
        run: bun run lint:css


# ---------------------------------------------------------------------


# Formating

  Formating:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install > log.txt 2>&1 || exit 1

      - name: Run bun fmt
        run: bun fmt >> log.txt 2>&1 || exit 1

      - name: Upload log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: log
          path: log.txt


# ---------------------------------------------------------------------


  # Building the website
  Build:
    runs-on: self-hosted
    needs: [Linting, Formating]
    steps:
      - uses: actions/checkout@v3
      # Install Dependenices
      - run: bun install
      # Build Website
      - run: bun run build
      # Add to NGINX
      - run: mv dist/ teaclientmc/
