# DO NOT TOUCH THIS FILE
# Please speak to SudoVanilla (Korbs) if you have any issues.
# For Security check please contact Eveeifyeve Instead of sudovanilla.

name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Deps
        run: bun install

      - name: Check stylelint
        run: bun stylelint

  CommitQuality:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: |
          bun install

      - name: Print versions
        run: |
          bun --version
          bunx commitlint --version
      - name: Install commitlint
        run: |
          bun install conventional-changelog-conventionalcommits
          bun install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bunx commitlint --from HEAD~1 --to HEAD --verbose

  Build:
    runs-on: self-hosted
    needs: [Quality, CommitQuality]
    steps:
      - uses: actions/checkout@v4
      # Install Dependenices
      - run: bun install
      # Build Website
      - run: bun run build
      # Add to NGINX
      - run: mv dist/ teaclientmc/