name: Pull Request Quality

on:
  pull_request:

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Deps
        run: bun install

      - name: Check stylelint
        run: bun stylelint

  CommitQuality:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: |
          bun install || true

      - name: Print versions
        run: |
          bun --version || true
          bunx commitlint --version || true
      - name: Install commitlint
        run: |
          bun install conventional-changelog-conventionalcommits || true
          bun install commitlint@latest || true

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bunx commitlint --from HEAD~1 --to HEAD --verbose || true

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose || true
