name: Pull Request Quality

on:
  pull_request:

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Deps
        run: bun install

      - name: Check stylelint
        run: bun stylelint

  CommitQuality:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: |
          bun install || echo "::warning::Warning: Failed to install packages"

      - name: Print versions
        run: |
          bun --version || echo "::warning::Warning: Failed to print bun version"
          bunx commitlint --version || echo "::warning::Warning: Failed to print commitlint version"
      - name: Install commitlint
        run: |
          bun install conventional-changelog-conventionalcommits || echo ::warning::"Warning: Failed to install conventional-changelog-conventionalcommits"
          bun install commitlint@latest || echo "::warning::Warning: Failed to install commitlint"

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: |
          bunx commitlint --from HEAD~1 --to HEAD --verbose || echo "::warning::Warning: Commitlint validation failed for the last commit"
